### ISSUE TITLE
Support server to server transfer

### ISSUE THREAD

**Issue by Bilge** [enl/flysystem-cloudinary#7] opened 2015-11-23 09:59 UTC
Cloudinary supports specifying the public HTTP endpoint for an image upload source. Your library assumes all uploaded images must come from a local source.

**Comment by danhunsaker** [comment] 2015-11-23 10:12
This library is merely an adapter layer for the Flysystem library, which is designed to give applications access to file storage systems in a uniform manner, so that apps can simply swap out which adapter is in use to switch storage systems.  For example, local storage during development, and Cloudinary in production.  It is beyond the scope of either project to fully support the Cloudinary API - this isn't an uploader, it's a filesystem abstraction.  So yes, everything is done from the application's perspective.  This is entirely by design.

**Comment by enl** [comment] 2016-04-24 16:39
Closing this with `wontfix`. Actually, @danhunsaker is right: server to server transfer is totally out of the scope of this project.

**Closed by enl** 2016-04-24 16:39 UTC
